### ISSUE TITLE
Support for enabling tap-to-click?

### ISSUE THREAD

**Issue by jurf** [Nano77/gdm3setup-utils#1]
Currently GDM comes with tap-to-click disabled by default (see [this bug](https://bugzilla.gnome.org/show_bug.cgi?id=747811)). It would be cool if it could be set by this.

Thanks!

**Comment by Nano77** [comment]
Implemented in c6a89d783e549bfc40f8c9c7909adc61a6965e56

**Comment by jurf** [comment]
Dude, you're a life saver. Thanks a lot.

**Comment by jurf** [comment]
Hm, tried `$ set_gdm -n TAP_TO_CLICK -v true` but nothing happened.

Also, will this get into the UI? And should I file requests like this here or in [dm3-setup](https://github.com/Nano77/gdm3setup)?

**Comment by Nano77** [comment]
set_gdm is not designed to be called directly by user
You call the dbus method SetTapToClick from apps.nano77.gdm3setup with d-feet or dbus-send
