### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/usr/share/gnome-shell/theme/gnome-shell.css'

### ISSUE THREAD

**Issue by lkhphuc** [Nano77/gdm3setup-utils#2]
Hello,
I am having problems using the gdmshelltheme to change the theme of gdm login screen instead of the grayish default gdm screen.
When I first run the gdmshelltheme -g to get current theme, it said that it can not find a file in /usr/share/gnome-shell/theme/gnome-shell.css. Because -g option cannot be executed, none of the other options can be executed except for -l listing option.
In my Gnome Tweak, it's say that this is my shell theme is Arctic Apricity and in the gdmshelltheme -l there is also a folder name Arctic Apricity ( as I'm currently running Apricity OS).
I've also tried to touch a new blank file in the missing directory /usr/share/gnome-shell/theme/gnome-shell.css, after that all the options of gdmshelltheme can be executed but nothing was changed in my login screen.
Thanks in advance.
Here is the the original error running gdmshelltheme -g:
`Traceback (most recent call last):
  File "/usr/bin/gdmshelltheme", line 73, in <module>
    print Get_Shell_theme()
  File "/usr/bin/gdmshelltheme", line 10, in Get_Shell_theme
    ifile = file('/usr/share/gnome-shell/theme/gnome-shell.css',"r")
IOError: [Errno 2] No such file or directory: '/usr/share/gnome-shell/theme/gnome-shell.css'
`

**Comment by wbs0829** [comment]
you can `sudo touch /usr/share/gnome-shell/theme/gnome-shell.css` and then run again.
